#连接Mirai的WS Url
connectUrl: ws://127.0.0.1:8080

#BDS路径
progressPath: C:\

#启动程序
progressName: bedrock_server_mod.exe

#Mirai连接key
key: ABCDEFG

#Mirai连接qq
qq: 114514

#发消息群聊
group: 
  - 1919810

#有权限操作机器人的qq
admin:
  - 114514

#关闭服务器的命令
stopCmd: stop

#最低输出等级
LoggerLevel: debug

#控制台自动染色
ConsoleColor: true

#配置文件版本(勿动)
Version: 4